/**
 *  Copyright Notice:
 *  Copyright 2021-2022 DMTF. All rights reserved.
 *  License: BSD 3-Clause License. For full text see link: https://github.com/DMTF/libspdm/blob/main/LICENSE.md
 **/

#include "test_crypt.h"

#if LIBSPDM_FFDHE_SUPPORT

/**
 * Validate Crypto DH Interfaces.
 *
 * @retval  true  Validation succeeded.
 * @retval  false  Validation failed.
 *
 **/
bool libspdm_validate_crypt_dh(void)
{
    bool result;
    void *dh1;
    void *dh2;

    uint8_t ff2048_pubkey1[256];
    size_t ff2048_pubkey1_len;
    uint8_t ff2048_pubkey2[256];
    size_t ff2048_pubkey2_len;
    uint8_t ff2048_com_key1[256];
    size_t ff2048_comkey1_len;
    uint8_t ff2048_com_key2[256];
    size_t ff2048_comkey2_len;

    uint8_t ff3072_pubkey1[384];
    size_t ff3072_pubkey1_len;
    uint8_t ff3072_pubkey2[384];
    size_t ff3072_pubkey2_len;
    uint8_t ff3072_com_key1[384];
    size_t ff3072_comkey1_len;
    uint8_t ff3072_com_key2[384];
    size_t ff3072_comkey2_len;

    uint8_t ffdhe3072_p[] ={
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xAD, 0xF8, 0x54, 0x58, 0xA2, 0xBB, 0x4A, 0x9A,
        0xAF, 0xDC, 0x56, 0x20, 0x27, 0x3D, 0x3C, 0xF1,
        0xD8, 0xB9, 0xC5, 0x83, 0xCE, 0x2D, 0x36, 0x95,
        0xA9, 0xE1, 0x36, 0x41, 0x14, 0x64, 0x33, 0xFB,
        0xCC, 0x93, 0x9D, 0xCE, 0x24, 0x9B, 0x3E, 0xF9,
        0x7D, 0x2F, 0xE3, 0x63, 0x63, 0x0C, 0x75, 0xD8,
        0xF6, 0x81, 0xB2, 0x02, 0xAE, 0xC4, 0x61, 0x7A,
        0xD3, 0xDF, 0x1E, 0xD5, 0xD5, 0xFD, 0x65, 0x61,
        0x24, 0x33, 0xF5, 0x1F, 0x5F, 0x06, 0x6E, 0xD0,
        0x85, 0x63, 0x65, 0x55, 0x3D, 0xED, 0x1A, 0xF3,
        0xB5, 0x57, 0x13, 0x5E, 0x7F, 0x57, 0xC9, 0x35,
        0x98, 0x4F, 0x0C, 0x70, 0xE0, 0xE6, 0x8B, 0x77,
        0xE2, 0xA6, 0x89, 0xDA, 0xF3, 0xEF, 0xE8, 0x72,
        0x1D, 0xF1, 0x58, 0xA1, 0x36, 0xAD, 0xE7, 0x35,
        0x30, 0xAC, 0xCA, 0x4F, 0x48, 0x3A, 0x79, 0x7A,
        0xBC, 0x0A, 0xB1, 0x82, 0xB3, 0x24, 0xFB, 0x61,
        0xD1, 0x08, 0xA9, 0x4B, 0xB2, 0xC8, 0xE3, 0xFB,
        0xB9, 0x6A, 0xDA, 0xB7, 0x60, 0xD7, 0xF4, 0x68,
        0x1D, 0x4F, 0x42, 0xA3, 0xDE, 0x39, 0x4D, 0xF4,
        0xAE, 0x56, 0xED, 0xE7, 0x63, 0x72, 0xBB, 0x19,
        0x0B, 0x07, 0xA7, 0xC8, 0xEE, 0x0A, 0x6D, 0x70,
        0x9E, 0x02, 0xFC, 0xE1, 0xCD, 0xF7, 0xE2, 0xEC,
        0xC0, 0x34, 0x04, 0xCD, 0x28, 0x34, 0x2F, 0x61,
        0x91, 0x72, 0xFE, 0x9C, 0xE9, 0x85, 0x83, 0xFF,
        0x8E, 0x4F, 0x12, 0x32, 0xEE, 0xF2, 0x81, 0x83,
        0xC3, 0xFE, 0x3B, 0x1B, 0x4C, 0x6F, 0xAD, 0x73,
        0x3B, 0xB5, 0xFC, 0xBC, 0x2E, 0xC2, 0x20, 0x05,
        0xC5, 0x8E, 0xF1, 0x83, 0x7D, 0x16, 0x83, 0xB2,
        0xC6, 0xF3, 0x4A, 0x26, 0xC1, 0xB2, 0xEF, 0xFA,
        0x88, 0x6B, 0x42, 0x38, 0x61, 0x1F, 0xCF, 0xDC,
        0xDE, 0x35, 0x5B, 0x3B, 0x65, 0x19, 0x03, 0x5B,
        0xBC, 0x34, 0xF4, 0xDE, 0xF9, 0x9C, 0x02, 0x38,
        0x61, 0xB4, 0x6F, 0xC9, 0xD6, 0xE6, 0xC9, 0x07,
        0x7A, 0xD9, 0x1D, 0x26, 0x91, 0xF7, 0xF7, 0xEE,
        0x59, 0x8C, 0xB0, 0xFA, 0xC1, 0x86, 0xD9, 0x1C,
        0xAE, 0xFE, 0x13, 0x09, 0x85, 0x13, 0x92, 0x70,
        0xB4, 0x13, 0x0C, 0x93, 0xBC, 0x43, 0x79, 0x44,
        0xF4, 0xFD, 0x44, 0x52, 0xE2, 0xD7, 0x4D, 0xD3,
        0x64, 0xF2, 0xE2, 0x1E, 0x71, 0xF5, 0x4B, 0xFF,
        0x5C, 0xAE, 0x82, 0xAB, 0x9C, 0x9D, 0xF6, 0x9E,
        0xE8, 0x6D, 0x2B, 0xC5, 0x22, 0x36, 0x3A, 0x0D,
        0xAB, 0xC5, 0x21, 0x97, 0x9B, 0x0D, 0xEA, 0xDA,
        0x1D, 0xBF, 0x9A, 0x42, 0xD5, 0xC4, 0x48, 0x4E,
        0x0A, 0xBC, 0xD0, 0x6B, 0xFA, 0x53, 0xDD, 0xEF,
        0x3C, 0x1B, 0x20, 0xEE, 0x3F, 0xD5, 0x9D, 0x7C,
        0x25, 0xE4, 0x1D, 0x2B, 0x66, 0xC6, 0x2E, 0x37,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
    };

    size_t ffdhe3072_g = 2;

    libspdm_my_print("\nCrypto DH Engine Testing:\n");

    /*FFDHE2048 test(dh_context parameters are generated by libspdm_dh_new_by_nid)*/
    ff2048_pubkey1_len = sizeof(ff2048_pubkey1);
    ff2048_pubkey2_len = sizeof(ff2048_pubkey2);
    ff2048_comkey1_len = sizeof(ff2048_com_key1);
    ff2048_comkey2_len = sizeof(ff2048_com_key2);
    libspdm_my_print("- Context1 ... ");
    dh1 = libspdm_dh_new_by_nid(LIBSPDM_CRYPTO_NID_FFDHE2048);
    if (dh1 == NULL) {
        libspdm_my_print("[Fail]");
        return false;
    }

    libspdm_my_print("Context2 ... ");
    dh2 = libspdm_dh_new_by_nid(LIBSPDM_CRYPTO_NID_FFDHE2048);
    if (dh2 == NULL) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        return false;
    }

    libspdm_my_print("Generate key1 ... ");
    result = libspdm_dh_generate_key(dh1, ff2048_pubkey1, &ff2048_pubkey1_len);
    if (!result || ff2048_pubkey1_len != 256) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Generate key2 ... ");
    result = libspdm_dh_generate_key(dh2, ff2048_pubkey2, &ff2048_pubkey2_len);
    if (!result || ff2048_pubkey2_len != 256) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Compute key1 ... ");
    result = libspdm_dh_compute_key(dh1, ff2048_pubkey2, ff2048_pubkey2_len,
                                    ff2048_com_key1, &ff2048_comkey1_len);
    if (!result || ff2048_comkey1_len != 256) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Compute key2 ... ");
    result = libspdm_dh_compute_key(dh2, ff2048_pubkey1, ff2048_pubkey1_len,
                                    ff2048_com_key2, &ff2048_comkey2_len);
    if (!result || ff2048_comkey2_len != 256) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Compare Keys ... ");
    if (ff2048_comkey1_len != ff2048_comkey2_len) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    if (libspdm_const_compare_mem(ff2048_com_key1, ff2048_com_key2, ff2048_comkey1_len) != 0) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("FFDHE2048 test [Pass]\n");
    libspdm_dh_free(dh1);
    libspdm_dh_free(dh2);


    /*FFDH_3072 test(dh_context parameters are set by libspdm_dh_set_parameter)*/
    ff3072_pubkey1_len = sizeof(ff3072_pubkey1);
    ff3072_pubkey2_len = sizeof(ff3072_pubkey2);
    ff3072_comkey1_len = sizeof(ff3072_com_key1);
    ff3072_comkey2_len = sizeof(ff3072_com_key2);

    /*Use FFDHE2048 generate dh_context */
    libspdm_my_print("- Context1 ... ");
    dh1 = libspdm_dh_new_by_nid(LIBSPDM_CRYPTO_NID_FFDHE2048);
    if (dh1 == NULL) {
        libspdm_my_print("[Fail]");
        return false;
    }

    libspdm_my_print("Context2 ... ");
    dh2 = libspdm_dh_new_by_nid(LIBSPDM_CRYPTO_NID_FFDHE2048);
    if (dh2 == NULL) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        return false;
    }

    /*Set FFDHE3072 parameter */
    libspdm_my_print("Set parameter1 ... ");
    if (!libspdm_dh_set_parameter(dh1, ffdhe3072_g, 8 * sizeof(ffdhe3072_p), ffdhe3072_p)) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Set parameter2 ... ");
    if (!libspdm_dh_set_parameter(dh2, ffdhe3072_g, 8 * sizeof(ffdhe3072_p), ffdhe3072_p)) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Generate key1 ... ");
    result = libspdm_dh_generate_key(dh1, ff3072_pubkey1, &ff3072_pubkey1_len);
    if (!result || ff3072_pubkey1_len != 384) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Generate key2 ... ");
    result = libspdm_dh_generate_key(dh2, ff3072_pubkey2, &ff3072_pubkey2_len);
    if (!result || ff3072_pubkey2_len != 384) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Compute key1 ... ");
    result = libspdm_dh_compute_key(dh1, ff3072_pubkey2, ff3072_pubkey2_len,
                                    ff3072_com_key1, &ff3072_comkey1_len);
    if (!result || ff3072_comkey1_len != 384) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Compute key2 ... ");
    result = libspdm_dh_compute_key(dh2, ff3072_pubkey1, ff3072_pubkey1_len,
                                    ff3072_com_key2, &ff3072_comkey2_len);
    if (!result || ff3072_comkey2_len != 384) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("Compare Keys ... ");
    if (ff3072_comkey1_len != ff3072_comkey2_len) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    if (libspdm_const_compare_mem(ff3072_com_key1, ff3072_com_key2, ff3072_comkey1_len) != 0) {
        libspdm_my_print("[Fail]");
        libspdm_dh_free(dh1);
        libspdm_dh_free(dh2);
        return false;
    }

    libspdm_my_print("FFDHE3072 test [Pass]\n");
    libspdm_dh_free(dh1);
    libspdm_dh_free(dh2);

    return true;
}

#endif /* LIBSPDM_FFDHE_SUPPORT */
