if(CMAKE_HOST_WIN32)
    set(CMAKE_C_COMPILER clang-cl.exe)
    set(CMAKE_LINKER lld-link.exe)
    if(ARCH STREQUAL "x64")
        set(CMAKE_C_FLAGS_INIT "-m64")
    elseif(ARCH STREQUAL "ia32")
        # A target triple, unlike -m32, is seen by CMake's compiler checks, which otherwise link
        # with /machine:x64.
        set(CMAKE_C_COMPILER_TARGET i686-pc-windows-msvc)
        set(CMAKE_C_FLAGS_INIT "-march=i586")
    endif()
elseif(CMAKE_HOST_APPLE)
    set(CMAKE_C_COMPILER clang)
    set(CMAKE_LINKER clang)
else()
    set(CMAKE_C_COMPILER clang)
    set(CMAKE_AR llvm-ar)
    set(CMAKE_RANLIB llvm-ranlib)
    set(CMAKE_LINKER clang)
    if(ARCH STREQUAL "x64")
        set(CMAKE_C_FLAGS_INIT "-m64 -mcmodel=small")
    elseif(ARCH STREQUAL "ia32")
        set(CMAKE_C_FLAGS_INIT "-m32")
        set(CMAKE_EXE_LINKER_FLAGS_INIT "-m32")
    endif()
endif()

list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ARCH)
