if(CMAKE_HOST_WIN32)
    set(CMAKE_C_COMPILER clang-cl.exe)
    set(CMAKE_LINKER lld-link.exe)
elseif(CMAKE_HOST_APPLE)
    set(CMAKE_C_COMPILER clang)
    set(CMAKE_LINKER clang)
else()
    set(CMAKE_C_COMPILER clang)
    set(CMAKE_AR llvm-ar)
    set(CMAKE_RANLIB llvm-ranlib)
    set(CMAKE_LINKER clang)
endif()
