# libspdm
CONFIG_LIBSPDM=y
CONFIG_LIBSPDM_REQUESTER=y
CONFIG_LIBSPDM_RESPONDER=y
CONFIG_LIBSPDM_CRYPTO_MBEDTLS=y
CONFIG_LIBSPDM_TRANSPORT_MCTP=y
CONFIG_LIBSPDM_DEBUG_ENABLE=y
CONFIG_LIBSPDM_SECRET_LIB_SAMPLE=y

# Ensure enough memory is available
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=131072
CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=131072

# libspdm prints a very verbose log. If you want to see it, remove
# the following two lines.
CONFIG_LOG=n
CONFIG_LIBSPDM_DEBUG_ENABLE=n
