name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
    #Changes to the following files do not trigger deployment
    paths-ignore:
     - 'os_stub/openssllib/openssl/**'
     - 'os_stub/mbedtlslib/mbedtls/**'
     - 'unit_test/cmockalib/cmocka/**'

env:
  BUILD_TYPE: Release

jobs:
  format_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # If any *.c *.h *.md file(except:mbedtls/openssl/cmocka) have Tab, the check will fail.
      - name: Check code format
        run: |
          if grep -rn "	" * --include=*.c --include=*.h --include=*.md;
          then exit 1
          fi

  gcc_mbedtls_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=mbedtls ..
          make copy_sample_key
          make -j2

      - name: Test Requester
        run: |
          cd build/bin
          ./test_spdm_requester

      - name: Test Responder
        run: |
          cd build/bin
          ./test_spdm_responder

  gcc_openssl_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=openssl ..
          make copy_sample_key
          make -j2

      - name: Test Requester
        run: |
          cd build/bin
          ./test_spdm_requester

      - name: Test Responder
        run: |
          cd build/bin
          ./test_spdm_responder

  VS2019_mbedtls_build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        #ilammy/msvc-dev-cmd@v1 is GitHub Action for configuring Developer Command Prompt for Microsoft Visual Studio on Windows.
        #This sets up the environment for compiling C/C++ code from command line.
      - name: Add msbuild to PATH
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Release -DCRYPTO=mbedtls ..
          nmake  copy_sample_key
          nmake
      - name: Test Requester
        run: |
          cd build/bin
          ./test_spdm_requester.exe
      - name: Test Responder
        run: |
          cd build/bin
          ./test_spdm_responder.exe

  VS2019_openssl_build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        #ilammy/msvc-dev-cmd@v1 is GitHub Action for configuring Developer Command Prompt for Microsoft Visual Studio on Windows.
        #This sets up the environment for compiling C/C++ code from command line.
      - name: Add msbuild to PATH
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Release -DCRYPTO=openssl ..
          nmake  copy_sample_key
          nmake
      - name: Test Requester
        run: |
          cd build/bin
          ./test_spdm_requester.exe
      - name: Test Responder
        run: |
          cd build/bin
          ./test_spdm_responder.exe
